/**
 * ═══════════════════════════════════════════════════════════
 * SysAI License Validation Module
 * ═══════════════════════════════════════════════════════════
 * 
 * Verifica le license key tramite IPC → electron.js → Node.js crypto
 * (Ed25519 non è supportato in Web Crypto API di Chromium/Electron)
 */

// ============================================================
// COSTANTI
// ============================================================
const LICENSE_STORAGE_KEY = 'sysai_license';
const LICENSE_PREFIX = 'SYSAI-';

// Tool che richiedono Pro
const PRO_TOOLS = [
  'configGenerator',
  'troubleshooter',
  'scriptBuilder',
  'securityAuditor',
];

// Tool sempre gratuiti
const FREE_TOOLS = [
  'logAnalyzer',
  'commandCrafter',
  'explainMode',
];

// ============================================================
// VERIFICA FIRMA VIA IPC (Node.js nativo)
// ============================================================

/**
 * Verifica la firma Ed25519 tramite il processo principale Electron
 * dove Node.js crypto supporta Ed25519 al 100%
 */
async function verifySignature(payloadB64, signatureB64) {
  try {
    // Usa IPC per chiamare Node.js crypto nel main process
    if (window.electron?.ipcRenderer?.invoke) {
      const result = await window.electron.ipcRenderer.invoke('verify-license', {
        payloadB64,
        signatureB64,
      });
      return result.valid === true;
    }

    // Fallback: se non siamo in Electron (dev mode nel browser)
    console.warn('[License] Non in Electron — verifica firma saltata (dev mode)');
    return false;
  } catch (err) {
    console.error('[License] Errore verifica firma:', err.message);
    return false;
  }
}

// ============================================================
// PARSING
// ============================================================

/**
 * Parsa una license key nelle sue componenti
 * Formato: SYSAI-[payload_base64url].[signature_base64url]
 */
function parseLicenseKey(key) {
  if (!key || typeof key !== 'string') return null;

  const trimmed = key.trim();

  if (!trimmed.startsWith(LICENSE_PREFIX)) return null;

  const body = trimmed.substring(LICENSE_PREFIX.length);

  const dotIndex = body.lastIndexOf('.');
  if (dotIndex === -1 || dotIndex === 0 || dotIndex === body.length - 1) return null;

  const payloadB64 = body.substring(0, dotIndex);
  const signatureB64 = body.substring(dotIndex + 1);

  try {
    // base64url → base64 standard per atob
    const b64std = payloadB64.replace(/-/g, '+').replace(/_/g, '/');
    const padding = '='.repeat((4 - (b64std.length % 4)) % 4);
    const payloadStr = atob(b64std + padding);
    const payload = JSON.parse(payloadStr);

    if (!payload.v || !payload.t || !payload.id || !payload.c) return null;
    if (!['pro', 'beta'].includes(payload.t)) return null;

    return { payloadB64, signatureB64, payload };
  } catch (err) {
    return null;
  }
}

// ============================================================
// VALIDAZIONE COMPLETA
// ============================================================

export async function validateLicense(key) {
  // 1. Parse
  const parsed = parseLicenseKey(key);
  if (!parsed) {
    return {
      valid: false,
      error: 'Invalid license key format',
    };
  }

  // 2. Verifica firma crittografica via IPC → Node.js
  const signatureValid = await verifySignature(parsed.payloadB64, parsed.signatureB64);
  if (!signatureValid) {
    return {
      valid: false,
      error: 'Invalid signature — this key was not generated by SysAI',
    };
  }

  // 3. Controlla scadenza
  if (parsed.payload.x) {
    const expiryDate = new Date(parsed.payload.x + 'T23:59:59Z');
    if (expiryDate < new Date()) {
      return {
        valid: false,
        error: `License expired on ${parsed.payload.x}`,
        expired: true,
        payload: parsed.payload,
      };
    }
  }

  // 4. Tutto ok!
  return {
    valid: true,
    type: parsed.payload.t,
    id: parsed.payload.id,
    email: parsed.payload.e,
    created: parsed.payload.c,
    expires: parsed.payload.x,
    isPro: true,
    payload: parsed.payload,
  };
}

// ============================================================
// STORAGE
// ============================================================

export function saveLicense(key) {
  try {
    localStorage.setItem(LICENSE_STORAGE_KEY, key.trim());
    return true;
  } catch (err) {
    console.error('[License] Errore salvataggio:', err.message);
    return false;
  }
}

export function loadLicense() {
  try {
    return localStorage.getItem(LICENSE_STORAGE_KEY) || null;
  } catch (err) {
    return null;
  }
}

export function removeLicense() {
  try {
    localStorage.removeItem(LICENSE_STORAGE_KEY);
    return true;
  } catch (err) {
    return false;
  }
}

// ============================================================
// API PUBBLICA
// ============================================================

export async function checkLicenseStatus() {
  const key = loadLicense();
  if (!key) {
    return {
      valid: false,
      type: 'free',
      isPro: false,
    };
  }

  const result = await validateLicense(key);

  if (!result.valid) {
    return {
      valid: false,
      type: 'free',
      isPro: false,
      error: result.error,
      expired: result.expired || false,
    };
  }

  return {
    valid: true,
    type: result.type,
    isPro: true,
    id: result.id,
    email: result.email,
    created: result.created,
    expires: result.expires,
    daysLeft: result.expires
      ? Math.ceil((new Date(result.expires + 'T23:59:59Z') - new Date()) / 86400000)
      : null,
  };
}

export async function isToolAvailable(toolName) {
  if (FREE_TOOLS.includes(toolName)) return true;

  if (PRO_TOOLS.includes(toolName)) {
    const status = await checkLicenseStatus();
    return status.isPro;
  }

  return true;
}

// Cache per check sincroni nella UI
let _cachedStatus = null;

export async function refreshLicenseCache() {
  _cachedStatus = await checkLicenseStatus();
  return _cachedStatus;
}

export function getCachedStatus() {
  return _cachedStatus || { valid: false, type: 'free', isPro: false };
}

export function isProCached() {
  return _cachedStatus?.isPro || false;
}

export async function activateLicense(key) {
  const result = await validateLicense(key);

  if (result.valid) {
    saveLicense(key);
    await refreshLicenseCache();
  }

  return result;
}

export async function deactivateLicense() {
  removeLicense();
  _cachedStatus = { valid: false, type: 'free', isPro: false };
  return _cachedStatus;
}

export { PRO_TOOLS, FREE_TOOLS };
